### ISSUE TITLE
Freeaim broken

### ISSUE THREAD

**Issue by SpiffyJUNIOR** [SpiffyJUNIOR/ArcCW#3]
example: https://cdn.discordapp.com/attachments/1113266616017363025/1119454155849863208/MedalTVGarrysMod20230616223046.mp4

**Comment by GarfieldLives** [comment]
https://github.com/SpiffyJUNIOR/ArcCW/assets/73044767/7ddf1099-214c-4272-b710-2a6bcff20144


https://github.com/SpiffyJUNIOR/ArcCW/assets/73044767/ab6151ff-bba4-4824-b3de-baa72ad48012


https://github.com/SpiffyJUNIOR/ArcCW/assets/73044767/c54e33d7-f362-47db-960e-e99a3dbd6918

more examples just to show how utterly fucking broken this shit is LOL

**Comment by SpiffyJUNIOR** [comment]
it was nowhere near this busted when i tested it, if i can't reproduce it then you'll have to send all your arccw config

**Comment by SpiffyJUNIOR** [comment]
not as broken as the above clips but it's definitely not working correctly

**Comment by SpiffyJUNIOR** [comment]
horizontal direction is messed up and it loops to the opposite max value if you go too far left or right

**Comment by SpiffyJUNIOR** [comment]
> horizontal direction is messed up and it loops to the opposite max value if you go too far left or right

nope it really is just like this even in default arccw, not fixing
